config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark,  only:[:show, :edit, :update, :destroy]
  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    def bookmark_params
      params.require(:bookmark).permit(:url, :title, :category, :description)
    end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(bookmark) do |f| %>
  
  <div class="field1">
    <%= f.label :URL %>
    <%= f.url_field :url, id: :bookmark_url %>
  </div>

  <div class="field2">
    <%= f.label :タイトル %>
    <%= f.text_field :title, id: :bookmark_title %>
  </div>

  <div class="field3">
    <%= f.label :カテゴリー %>
    <%= f.text_field :category, id: :bookmark_category %>
  </div>

  <div class="field4">
    <%= f.label :説明 %>
    <%= f.text_field :description, id: :bookmark_description %>
  </div>

  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>編集</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to '戻る', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>ブックマーク管理アプリ</h1>
    
<table>
  <thead>
    <tr>
      <th>URL</th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.url %></td>
        <td><%= link_to '確認', bookmark %></td>
        <td><%= link_to '編集', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to '削除', bookmark, method: :delete, data: { confirm: '削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to '戻る', bookmarks_path %> 

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<h1>確認</h1>
<p>
  <strong>URL:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>カテゴリー:</strong>
  <%= @bookmark.category %>
</p>

<p>
  <strong>説明:</strong>
  <%= @bookmark.description %>
</p>

<%= link_to '編集', edit_bookmark_path(@bookmark) %> |
<%= link_to '一覧へ', bookmarks_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SBS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list/help.html.erb
<h1>List#help</h1>
<p>Find me in app/views/list/help.html.erb</p>

app/views/list/home.html.erb
<% provide(:title, "Home") %>

<header>
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "お気に入り",   '#' %></li>
      </ul>
    </nav>
  </div>

  <div class="Configuration">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "設定",   '#' %></li>
      </ul>
    </nav>
  </div>
  
  <div class="Register">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <%= link_to "新規登録",   '#' %>
      </ul>
    </nav>
  </div>
</header>

<footer>
</footer>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>